# Generated by Django 4.2.30 on 2026-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_points_value_game_win_type_match_game_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='crawford_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='cube_owner',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='cube_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='double_offered_by',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
