# Generated by Django 4.2.30 on 2026-07-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_crawford_game_game_cube_owner_game_cube_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
