# Generated by Django 4.2.30 on 2026-08-03 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Add the per-account preference table, whose only field today is the
    turn-reminder-email opt-out.

    **No backfill, deliberately.** Every existing account gets no row, and
    "no row" is defined to mean "all defaults" everywhere it is read
    (``UserPreferences.reminders_enabled``, ``UserSerializer``), so a backfill
    would insert several thousand rows to express exactly what their absence
    already expresses. Rows appear lazily, on the first PATCH that changes a
    preference. That also keeps this migration O(1) on the Postgres cutover.

    Reversing drops the table and every opt-out in it — the surviving state is
    "everyone opted in", which is the default, so a reverse-then-reapply
    silently re-enrols anyone who had switched reminders off.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_game_turn_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_reminder_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user preferences',
            },
        ),
    ]
